site_name: Monolyth documentation
site_url: http://monolyth.monomelodies.nl/
repo_url: https://github.com/monomelodies/monolyth

pages:
- Home:
    - 'Overview': 'index.md'

copyright: Copyright &copy; 2002-2015, <a href="http://monomelodies.nl/">Marijn Ophorst</a>

