site_name: Monolyth documentation
site_url: http://monolyth.monomelodies.nl/docs/
repo_url: https://github.com/monomelodies/monolyth

pages:
- Home:
    - 'Quickstart': 'index.md'
- Demo site:
    - 'Prerequisites': 'demo/prerequisites.md'
    - 'Dependencies': 'demo/dependencies.md'
    - 'Routing': 'demo/routing.md'
    - 'Views': 'demo/view.md'
    - 'Controllers': 'demo/controller.md'
- Packages:
    - 'Required packages': 'packages/required.md'
    - 'Optional packages': 'packages/optional.md'

