site_name: Example documentation
site_url: http://example.com/
repo_url: https://github.com/author/package

pages:
- Home:
    - 'Quickstart': 'index.md'

copyright: Copyright &copy; 2015, <a href="http://example.com/">Joe Developer</a>

