site_name: Monolyth Frontal documentation
site_url: http://monolyth.monomelodies.nl/frontal/
repo_url: https://github.com/monolyth-php/frontal/

pages:
- Home:
    - 'Overview': 'index.md'

copyright: Copyright &copy; 2002-2016, <a href="http://monomelodies.nl/">Marijn Ophorst</a>

